### PR TITLE
Issue #2: Fake pattern-specific data

### PR DESCRIPTION
**Pull request by AndyIRC**
This seems to fix Issue #2. I just listen to an event dispatched later - by that time the pattern specific data is in the array.

### CODE REVIEW

**Comment by sh-avonis** [comment]
+1

**Review by nerfchicken — APPROVED** [review]
This worked for me to generate pattern specific data.

**Comment by willthemoor** [comment]
Works for me as well. Thank you! 

@EvanLovely Consider merging this? Please? :)

**Comment by pcate-coreonyx** [comment]
This PR worked for me as well. Would love to see it merged.

**Comment by EvanLovely** [comment]
Released in: https://github.com/pattern-lab/plugin-php-faker/releases/tag/v2.0.2

Sorry it took so long!

**Comment by pcate-coreonyx** [comment]
New composer packagist release?

**Pull request merged**
